093 海岩第一个作业试运行。。。
ggl-smt-4th/Team_J pull request #6
Opened 2018-06-19 05:54 UTC by MicKing110

2018-06-19 10:05 UTC, MicKing110 commented
第一课

2018-06-21 04:19 UTC, minzhi3 requested changes
要改的地方比较多，可以看看其他同学PR的代码
另外作业要放到指定目录下面 
Lesson-1/assignment/

2018-06-21 04:19 UTC, minzhi3 commented on haiyan.sol
> +contract paoyroll{
首先这个合约应该有全个employer变量作为老板的地址，不然任何人都可以执行变更工资和员工地址的行为
可以参加下其他同学的代码

2018-06-21 04:19 UTC, minzhi3 commented on haiyan.sol
> +       return salary=money  * 1 ether;
变更工资前要先结算一下之前没结的工资

2018-06-21 04:19 UTC, minzhi3 commented on haiyan.sol
> +    address frank ;
应该有一个函数用于变更frank的地址

2018-06-25 11:33 UTC, minzhi3 requested changes
作业记得把sample另存一个Payroll.sol
另外优化后updateEmployee和removeEmployee也要加上totalSalary的修改

2018-06-25 11:33 UTC, minzhi3 commented on projects/lesson-2/home-work.md
> +每次消耗的都是一样gas
优化前随着员工人数增加这个值是会增大的，你看看会不会是一开始就加了10个

2018-07-03 05:14 UTC, merged