095_刘培骢_第一节课作业
ggl-smt-4th/Team_J pull request #7
Opened 2018-06-19 22:11 UTC by wade2999

Created a contract for employer to pay salary to one employee. Employer can update salary and employee address, and employee could get payment by calling getPaid.

2018-06-20 11:09 UTC, minzhi3 requested changes
大方向基本对，updateEmployeeAddress函数的逻辑有点问题
另外作业要移到指定目录下

2018-06-20 11:09 UTC, minzhi3 commented on EmployeeSalaryContract.sol
> +            employee.transfer(this.balance);
从安全上讲最好把transfer语句放到末尾
另外this.balance是合约里所有的钱，这样写employee就赚翻了。
应该先计算employee没拿到手（getPaid）的部分工资

2018-06-20 11:09 UTC, minzhi3 commented on EmployeeSalaryContract.sol
> +        salary = newSalary;
这里也应该和updateEmployeeAddress一样按旧工资先结算一次

2018-06-22 02:59 UTC, closed without merging

2018-06-22 03:01 UTC, wade2999 commented
我重新rebase了一下master，之前只有一个readme file